sudo: required
dist: trusty
language: cpp

services:
  - docker

before_install:
  - docker build -t build_ref -f tools/docker_image .

script:
  - docker run build_ref /bin/bash -c "tools/clang_format_check.sh"

  # Build debug and release with Clang and run tests
  - docker run build_ref /bin/bash -c "mkdir build-clang-debug && cd build-clang-debug && CXX=clang++ cmake .. && make -j$(nproc) && ctest --output-on-failure"
  - docker run build_ref /bin/bash -c "mkdir build-clang-release && cd build-clang-release && CXX=clang++ cmake .. -DCMAKE_BUILD_TYPE=Release && make -j$(nproc) && ctest --output-on-failure"

  # Build debug and release with GCC and run tests
  - docker run build_ref /bin/bash -c "mkdir build-gcc-debug && cd build-gcc-debug && CXX=g++ cmake .. && make -j$(nproc) && ctest --output-on-failure"
  - docker run build_ref /bin/bash -c "mkdir build-gcc-release && cd build-gcc-release && CXX=g++ cmake .. -DCMAKE_BUILD_TYPE=Release && make -j$(nproc) && ctest --output-on-failure"

